setrlimit fd 65535, fix when fdlimit reached

diff --git a/debian/rum/etc/init.d/rum b/debian/rum/etc/init.d/rum
--- a/debian/rum/etc/init.d/rum
+++ b/debian/rum/etc/init.d/rum
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 ### BEGIN INIT INFO
 # Provides:          rum
 # Required-Start:    $network $local_fs
@@ -13,6 +13,7 @@
 ### END INIT INFO
 
 # Author: Tomas Corej <tomas.corej@websupport.sk>
+# Author: Matus Bursa <matus.bursa@eset.sk>
 
 # PATH should only include /usr/* if it runs after the mountnfs.sh script
 PATH=/sbin:/usr/sbin:/bin:/usr/bin
@@ -50,19 +51,18 @@ do_start()
 	do
 		PIDFILE=/var/run/${instance%%:*}.pid
 		DAEMON_ARGS=${instance#*:}
-			start-stop-daemon --start -m --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
-				|| return 1
-			start-stop-daemon --start -m --quiet --pidfile $PIDFILE --exec $DAEMON -- \
+			start-stop-daemon --start -m --quiet -N -20 --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
+				||  log_warning_msg "daemon was already running"
+			start-stop-daemon --start -m --quiet -N -20 --pidfile $PIDFILE --exec $DAEMON -- \
 				$DAEMON_ARGS \
-				|| return 2
+				|| log_failure_msg "daemon could not be started"
 		# Add code here, if necessary, that waits for the process to be ready
 		# to handle requests from services started subsequently which depend
 		# on this one.  As a last resort, sleep for some time.
 
 		# rum forks itself to background so pid is always about one off
 		PID=`cat $PIDFILE`
-		PID=$((PID+1))
-		echo $PID > $PIDFILE
+		echo $((PID+1)) > $PIDFILE
 	done
 }
 
@@ -92,6 +92,7 @@ do_stop()
 		# Many daemons don't delete their pidfiles when they exit.
 		[ -f $PIDFILE ] && rm -f $PIDFILE
 	done
+	rm -f /var/run/rum*.pid
 	unset IFS
 	return 0
 }
@@ -105,7 +106,81 @@ do_reload() {
 	# restarting (for example, when it is sent a SIGHUP),
 	# then implement that here.
 	#
+	grep -v ^# /etc/default/$NAME | \
+        while read instance
+	do
+		PIDFILE=/var/run/${instance%%:*}.pid
+		PROCESS=$(cat $PIDFILE 2> /dev/null)
+		PROCESS_NAME=$(ps -p $PROCESS -o comm= 2> /dev/null)	
+
+		PROCESS_ARGS=$(ps -p $PROCESS -o args= 2> /dev/null)
+		DAEMON_ARGS=${instance#*:}
+	
+		if [ "rum" != "$PROCESS_NAME" ]; then
+			# kill whatever it is and run our rum instance
+			log_daemon_msg "Reloading $DESC" "${instance%%:*}"
+			# TCP only for now
+			if [[ $DAEMON_ARGS =~ ^.*\-\s\ +tcp:(([0-9]{1,3}.){3}[0-9]{1,3}:[0-9]+)\ .+$ ]]; then
+				IPPORT=${BASH_REMATCH[1]}
+				PID=`lsof -i4@$IPPORT -sTCP:LISTEN -t`
+				if [[ $PID =~ ^([0-9]+)$ ]]; then
+					PID=${BASH_REMATCH[1]}
+					kill $PID
+					sleep 3
+				fi	
+			unset IPPORT
+			unset PID
+			fi
+			# start not running process
+			start-stop-daemon --start -m --quiet -N -20 --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_ARGS 
+			PID=`cat $PIDFILE`
+		        echo $((PID+1)) > $PIDFILE
+			continue
+		elif [ "$DAEMON $DAEMON_ARGS" != "$PROCESS_ARGS" ]; then
+			log_daemon_msg "Reloading $DESC" "${instance%%:*}"
+				# stop running process with bad arguments
+			start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
+			start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE --retry=0/30/KILL/5 --exec $DAEMON
+			[ -f $PIDFILE ] && rm -f $PIDFILE
+			
+			# start process
+			start-stop-daemon --start -m --quiet -N -20 --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_ARGS 
+                        PID=`cat $PIDFILE`
+                        echo $((PID+1)) > $PIDFILE
+		fi
+	done
 	return 0
+}
+
+do_status() {
+	grep -v ^# /etc/default/$NAME | \
+	( retn=0 ;
+        while read instance
+        do
+		PIDFILE=/var/run/${instance%%:*}.pid
+                PROCESS=$(cat $PIDFILE 2> /dev/null)
+                PROCESS_NAME=$(ps -p $PROCESS -o comm= 2> /dev/null)
+
+                PROCESS_ARGS=$(ps -p $PROCESS -o args= 2> /dev/null)
+                DAEMON_ARGS=${instance#*:}
+
+		if [ "rum" != "$PROCESS_NAME" ]; then
+			if [ "$SILENT" != "yes" ]; then 
+				echo ${instance%%:*} is not running
+			fi
+			retn=1
+		elif [ "$DAEMON $DAEMON_ARGS" != "$PROCESS_ARGS" ]; then
+			if [ "$SILENT" != "yes" ]; then 
+				echo ${instance%%:*} is running with bad arguments
+			fi
+			retn=2
+		else
+			if [ "$SILENT" != "yes" ]; then 
+				echo ${instance%%:*} is running
+			fi
+		fi
+	done
+	return $retn )
 }
 
 case "$1" in
@@ -126,17 +201,23 @@ case "$1" in
 	esac
 	;;
   status)
-       status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+	do_status
+	exit $?
        ;;
-  #reload|force-reload)
+  silentstatus)
+	SILENT="yes"
+	do_status
+	exit $?
+       ;;
+  reload|force-reload)
 	#
 	# If do_reload() is not implemented then leave this commented out
 	# and leave 'force-reload' as an alias for 'restart'.
 	#
 	#log_daemon_msg "Reloading $DESC" "$NAME"
-	#do_reload
+	do_reload
 	#log_end_msg $?
-	#;;
+	;;
   restart|force-reload)
 	#
 	# If the "reload" option is implemented then remove the
@@ -161,7 +242,7 @@ case "$1" in
 	;;
   *)
 	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
-	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+	echo "Usage: $SCRIPTNAME {start|stop|silentstatus|status|reload|restart|force-reload}" >&2
 	exit 3
 	;;
 esac
